const email=localStorage.getItem('salonnext_email');
if(!email) location.replace('/login.html');
const $=selector=>document.querySelector(selector);
const form=$('#planner'), rows=$('#post-rows'), statusEl=$('#status'), resultEl=$('#result');
const visitorId=localStorage.getItem('salonnext_visitor')||crypto.randomUUID();
localStorage.setItem('salonnext_visitor',visitorId);
$('#signed-in').textContent=email||'Demo visitor';$('#avatar').textContent=(email||'S').charAt(0).toUpperCase();
$('#sign-out').addEventListener('click',()=>{localStorage.removeItem('salonnext_email');location.href='/login.html';});
$('#menu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
document.querySelectorAll('.sidebar nav a').forEach(a=>a.addEventListener('click',()=>$('.sidebar').classList.remove('open')));
function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function addPost(post={}){
  const tr=document.createElement('tr');
  tr.innerHTML=`<td><input aria-label="Post caption or topic" data-key="caption" maxlength="280" placeholder="e.g. Bridal bun transformation" value="${escapeHTML(post.caption||'')}"></td>${['reach','likes','comments','saves','shares'].map(k=>`<td><input aria-label="${k}" data-key="${k}" type="number" min="0" step="1" value="${post[k]??''}"></td>`).join('')}<td><button type="button" aria-label="Remove post" title="Remove post">×</button></td>`;
  tr.querySelector('button').addEventListener('click',()=>{tr.remove();saveDraft();updateMetrics();});
  tr.querySelectorAll('input').forEach(x=>x.addEventListener('input',()=>{saveDraft();updateMetrics();}));
  rows.append(tr);updateMetrics();
}
function posts(){return [...rows.querySelectorAll('tr')].map(tr=>Object.fromEntries([...tr.querySelectorAll('input')].map(i=>[i.dataset.key,i.type==='number'&&i.value!==''?Number(i.value):i.value.trim()]))).filter(p=>p.caption);}
function rates(){return posts().map(p=>({...p,rate:p.reach>0?((Number(p.likes)||0)+(Number(p.comments)||0)+(Number(p.saves)||0)+(Number(p.shares)||0))/p.reach:null}));}
function updateMetrics(){const p=rates(), scored=p.filter(x=>x.rate!==null).sort((a,b)=>a.rate-b.rate);$('#metric-posts').textContent=p.length;$('#metric-engagement').textContent=scored.length?`${(((scored[Math.floor((scored.length-1)/2)].rate+scored[Math.floor(scored.length/2)].rate)/2)*100).toFixed(1)}%`:'—';$('#metric-angle').textContent=scored.length?scored[scored.length-1].caption.slice(0,36):p.length?'Metrics missing':'Add posts';}
function saveDraft(){const fd=new FormData(form), values=Object.fromEntries(fd.entries());localStorage.setItem('salonnext_draft',JSON.stringify({values,posts:posts()}));}
form.addEventListener('input',saveDraft);
$('#add-post').addEventListener('click',()=>addPost());
$('#sample').addEventListener('click',()=>{const sample={salon_name:'Saffron Studio',salon_type:'Hair salon',location:'Bandra, Mumbai',audience:'working professionals and wedding guests',services:'balayage, occasion styling, hair repair',goal:'Increase bookings',filming_time:'30 minutes',voice:'Warm and expert',language:'English',competitors:'A nearby salon posts bridal transformations; another shares quick hair-care tips. These are observations, not verified performance data.',trend_notes:'monsoon frizz and wedding guest hair'};for(const [key,value] of Object.entries(sample))form.elements[key].value=value;rows.innerHTML='';[{caption:'Bridal guest hair transformation',reach:5100,likes:248,comments:22,saves:79,shares:28},{caption:'Three ways to handle monsoon frizz',reach:4200,likes:172,comments:18,saves:95,shares:31},{caption:'Balayage before and after',reach:6900,likes:310,comments:25,saves:67,shares:20},{caption:'Monday discount offer',reach:1800,likes:42,comments:3,saves:8,shares:2}].forEach(addPost);saveDraft();statusEl.textContent='Fictional sample loaded. Replace it with your own salon data when ready.';});
function parseCSV(text){const lines=[];let current='',row=[],quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){current+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(current);current='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(current);if(row.some(v=>v.trim()))lines.push(row);row=[];current='';}else current+=c;}row.push(current);if(row.some(v=>v.trim()))lines.push(row);if(lines.length<2)return[];const headers=lines.shift().map(x=>x.trim().toLowerCase().replace(/\s+/g,'_'));const captionIndex=headers.findIndex(x=>['caption','topic','description'].includes(x));if(captionIndex<0)throw new Error('CSV needs a caption or topic column.');return lines.slice(0,30).map(items=>{const p={caption:(items[captionIndex]||'').trim()};for(const k of ['reach','likes','comments','saves','shares']){const ix=headers.indexOf(k);if(ix>=0&&items[ix]!==undefined&&items[ix]!=='')p[k]=Number(items[ix].replaceAll(',',''))||0;}return p;}).filter(p=>p.caption);}
$('#csv').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const imported=parseCSV(await file.text());if(!imported.length)throw new Error('No posts found in that CSV.');rows.innerHTML='';imported.forEach(addPost);saveDraft();statusEl.textContent=`Imported ${imported.length} posts.`;}catch(error){statusEl.textContent=error.message;}e.target.value='';});
try{const draft=JSON.parse(localStorage.getItem('salonnext_draft')||'null');if(draft){for(const [key,value] of Object.entries(draft.values||{})){if(form.elements[key])form.elements[key].value=value;}for(const post of draft.posts||[])addPost(post);}}catch{}if(!rows.children.length)addPost();
function safeLink(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function renderResult(data){const x=data.recommendation||{}, analytics=data.analytics||{}, research=data.research||{};const sources=(research.sources||[]).map(s=>{const href=safeLink(s.url);return href?`<a href="${escapeHTML(href)}" target="_blank" rel="noopener noreferrer">${escapeHTML(s.title||new URL(href).hostname)} ↗</a>`:'';}).join('');const scoreText=Object.entries(x.scores||{}).map(([key,value])=>`<span class="score">${escapeHTML(key.replaceAll('_',' '))} · ${Math.round(Number(value)*100)}%</span>`).join('');const storyboard=Array.isArray(x.storyboard)?x.storyboard.join(' • '):x.storyboard;
  resultEl.innerHTML=`<div class="result-head"><div><p class="eyebrow">Your next move · ${escapeHTML(x.format||'Reel')}</p><h2>${escapeHTML(x.title||'Your next Reel')}</h2><p>${escapeHTML(x.angle||'')}</p></div><span class="badge">${escapeHTML(x.effort||'Film this week')}</span></div><div class="evidence"><article><small>Why this fits your salon</small><p>${escapeHTML(x.why_you||'')}</p></article><article><small>Why now</small><p>${escapeHTML(x.why_now||'')}</p></article></div><div class="research-card"><small>Competitor angle</small><p>${escapeHTML(x.competitor_gap||"No verified comparable salon observation was available.")}</p></div><p class="hint">Fit scores are heuristic; expected engagement uses a neutral 50% prior, not a prediction.</p><div class="scores">${scoreText}</div><div class="content-grid"><div class="content-block"><small>Hook · first 3 seconds</small><p>${escapeHTML(x.hook||'')}</p></div><div class="content-block"><small>Spoken script</small><p>${escapeHTML(x.script||'')}</p></div><div class="content-block wide"><small>Shot-by-shot plan</small><p>${escapeHTML(storyboard||'')}</p></div><div class="content-block"><small>Caption</small><p>${escapeHTML(x.caption||'')}</p></div><div class="content-block"><small>Call to action</small><p>${escapeHTML(x.cta||'')}</p></div></div><div class="research-card"><small>Evidence receipt</small><p>${escapeHTML(x.evidence_note||research.summary||'')}</p>${sources?`<div class="source-list">${sources}</div>`:''}<p class="hint">${escapeHTML(analytics.summary||'')}</p></div>${(data.alternatives||[]).length?`<div class="alternate"><h3>Other angles considered</h3><ul>${data.alternatives.map(a=>`<li>${escapeHTML(a.title)} — ${escapeHTML(a.angle)}</li>`).join('')}</ul></div>`:''}`;
  resultEl.hidden=false;resultEl.scrollIntoView({behavior:'smooth',block:'start'});$('#metric-total').textContent=data.usage?.total_requests??'—';
}
form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const button=$('#generate');button.disabled=true;button.textContent='Researching and ranking…';statusEl.textContent='Reading your post patterns, checking niche signals and preparing your filming plan. This can take a little while.';resultEl.hidden=true;const fd=new FormData(form);const input={visitor_id:visitorId,...Object.fromEntries(fd.entries()),posts:posts()};try{const response=await fetch('/api/recommend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to make a recommendation.');renderResult(data);statusEl.textContent=`Recommendation ready · ${data.usage?.requests_remaining??0} demo requests left for this browser.`;}catch(error){statusEl.textContent=error.message||'Unable to generate. Please try again.';}finally{button.disabled=false;button.textContent='Find my next Reel ↗';}});
fetch('/api/recommend').then(r=>r.json()).then(d=>{$('#metric-total').textContent=d.total_requests??'—';}).catch(()=>{});
