const LIMIT = 5;
const MODEL = 'gemini-3.5-flash-lite';

function headers() { return { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'content-type' }; }
function supabaseBase() { return `${process.env.SUPABASE_URL}/rest/v1/salonnext_requests`; }
async function supabase(path = '', options = {}) { const r = await fetch(`${supabaseBase()}${path}`, { ...options, headers: { apikey: process.env.SUPABASE_SERVICE_KEY, Authorization: `Bearer ${process.env.SUPABASE_SERVICE_KEY}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); if (!r.ok) throw new Error(`Supabase request failed (${r.status})`); return r; }
async function countRequests(visitorId) { const filter = visitorId ? `&visitor_id=eq.${encodeURIComponent(visitorId)}` : ''; const r = await supabase(`?select=id${filter}`, { headers: { Prefer: 'count=exact', Range: '0-0' } }); const range = r.headers.get('content-range') || '*/0'; return Number(range.split('/')[1] || 0); }
function fallback(input) { return { title: `The ${input.goal.toLowerCase()} mini-series`, why_now: 'This first prototype uses your stated goal and recent patterns as the strongest available evidence. Trend evidence is thin until live market research is connected, so treat this as a testable hypothesis.', scores: { creator_fit: .82, audience_demand: .62, trend_momentum: .48, novelty: .73, expected_engagement: .58 }, hook: `If you are a ${input.audience.toLowerCase()} customer, save this before your next salon visit.`, storyboard: `Open with the finished result; show three quick steps from ${input.recent_patterns.split(',')[0] || 'your signature service'}; finish with a local booking invitation.`, caption: `A practical ${input.goal.toLowerCase()} idea for ${input.salon_type.toLowerCase()} clients. Which look would you try?`, cta: 'DM “NEXT” to ask about availability this week.', evidence_note: 'Illustrative cold-start recommendation. The model had no connected Instagram analytics or live trend source for this request.' }; }
const schema = { type: 'object', properties: { title:{type:'string'}, why_now:{type:'string'}, scores:{type:'object',properties:{creator_fit:{type:'number'},audience_demand:{type:'number'},trend_momentum:{type:'number'},novelty:{type:'number'},expected_engagement:{type:'number'}},required:['creator_fit','audience_demand','trend_momentum','novelty','expected_engagement']}, hook:{type:'string'}, storyboard:{type:'string'}, caption:{type:'string'}, cta:{type:'string'}, evidence_note:{type:'string'} }, required:['title','why_now','scores','hook','storyboard','caption','cta','evidence_note'] };
async function generate(input) { if (!process.env.GEMINI_API_KEY) return { recommendation:fallback(input), inputTokens:0, outputTokens:0 }; const system = `You are SalonNext, a salon content recommendation engine adapted from CreatorOS. Return exactly one ready-to-film Instagram Reel recommendation. Apply five independent normalized scores from 0 to 1: creator_fit (matches the stated salon and its recent patterns), audience_demand (fit with the stated audience), trend_momentum (only claim momentum when supported; otherwise keep it moderate), novelty (not a copy of recent patterns), expected_engagement (a cautious cold-start estimate). Never invent analytics, sources, or guarantees. If recent_patterns is abusive, unrelated to salons, or asks for unsafe content, refuse that request and return a safe salon content suggestion. Keep every field concise. `; const prompt = `${system}\n\nSalon type: ${input.salon_type}\nAudience: ${input.audience}\nRecent post patterns: ${input.recent_patterns}\nGoal: ${input.goal}`; const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':process.env.GEMINI_API_KEY},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',responseSchema:schema,maxOutputTokens:500}})}); if(!r.ok) throw new Error('Gemini request failed'); const data=await r.json(); const text=data.candidates?.[0]?.content?.parts?.[0]?.text; if(!text) throw new Error('Gemini returned no recommendation'); return { recommendation:JSON.parse(text), inputTokens:data.usageMetadata?.promptTokenCount||0, outputTokens:data.usageMetadata?.candidatesTokenCount||0 }; }
module.exports = async (req, res) => { if (req.method === 'OPTIONS') return res.status(204).setHeader('Access-Control-Allow-Origin','*').end(); try { if (req.method === 'GET') { const total = await countRequests(null).catch(()=>0); return res.status(200).setHeader('Content-Type','application/json').json({ total_requests: total }); } if (req.method !== 'POST') return res.status(405).setHeader('Allow','POST').json({error:'POST only'}); const input=req.body||{}; for (const k of ['visitor_id','salon_type','audience','recent_patterns','goal']) if(typeof input[k]!=='string'||!input[k].trim()) return res.status(400).setHeader('Access-Control-Allow-Origin','*').json({error:`Please provide ${k.replaceAll('_',' ')}`}); const visitorCount=await countRequests(input.visitor_id); if(visitorCount>=LIMIT) return res.status(429).setHeader('Access-Control-Allow-Origin','*').json({error:`This visitor has reached the ${LIMIT}-request demo cap.`}); const generated=await generate(input); const recommendation=generated.recommendation; await supabase('',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({visitor_id:input.visitor_id,salon_type:input.salon_type,audience:input.audience,recent_patterns:input.recent_patterns,goal:input.goal,input_payload:input,output_payload:recommendation,input_tokens:generated.inputTokens,output_tokens:generated.outputTokens,model:process.env.GEMINI_API_KEY?MODEL:'fallback-cold-start'})}); const total=await countRequests(null).catch(()=>visitorCount+1); return res.status(200).setHeader('Access-Control-Allow-Origin','*').json({recommendation,usage:{total_requests:total,requests_remaining:LIMIT-visitorCount-1,input_tokens:generated.inputTokens,output_tokens:generated.outputTokens}}); } catch(e) { return res.status(500).setHeader('Access-Control-Allow-Origin','*').json({error:e.message||'Unable to generate recommendation'}); } };

